# 1장 데이터 분석을 시작하며
##### (1) 데이터 분석이란
##### (2) 구글 코랩과 주피터 노트북
##### (3) 이 도서가 얼마나 인기가 좋을까요?

In [2]:
output ="서울특별시교육청남산도서관 장서 대출목록 (2026년 06월).csv"
import pandas as pd
df = pd.read_csv(output, encoding='utf-8')
print(df.head())

   번호        도서명             저자         출판사  발행년도           ISBN  세트 ISBN  \
0   1  플로우=Flow     긴츠 질발로디스 감독       노바미디어  2025  8809866320916      NaN
1   2        투게더     마이클 생크스 감독  디온(The On)  2026  8800279440390      NaN
2   3     코트 스틸링   대런 아로노프스키 감독       소니픽쳐스  2026  8809763865411      NaN
3   4   총알 탄 사나이      아키바 샤퍼 감독       파라마운트  2025  8809931179425      NaN
4   5    인비저블 보이  가브리엘 살바토레스 감독      유케이미디어  2026  8800240308209      NaN

  부가기호    권 주제분류번호  도서권수  대출건수        등록일자  Unnamed: 13
0  NaN  NaN  688.2     1     0  2026-06-30          NaN
1  NaN  NaN  688.2     1     0  2026-06-30          NaN
2  NaN  NaN  688.2     1     0  2026-06-30          NaN
3  NaN  NaN  688.2     1     0  2026-06-30          NaN
4  NaN  NaN  688.2     1     0  2026-06-30          NaN

C:\Users\yccho\AppData\Local\Temp\ipykernel_21080\4197475141.py:3: DtypeWarning: Columns (0: ISBN, 1: 부가기호, 2: 주제분류번호) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(output, encoding='utf-8')

In [3]:
with open(output, encoding="utf-8") as f:
    print(f.readline()) #한 줄만 읽어옴
    print(f.readline())

번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자,

"1","플로우=Flow ","긴츠 질발로디스 감독","노바미디어","2025","8809866320916","","","","688.2","1","0","2026-06-30",

In [4]:
#파일 인코딩 형식 확인하기
import chardet
with open(output, 'rb') as f:
    d=f.readline()
    print(chardet.detect(d))

{'encoding': 'UTF-8-SIG', 'confidence': 1.0, 'language': 'ko', 'mime_type': 'text/plain'}

* CSV 파일을 데이터프레임으로 읽기: read_csv()

In [5]:
import pandas as pd
#df = pd.read_csv(output, encoding='utf-8') #5,7,9열은 혼합된 데이터가 저장되어 있음을 경고함->파일 내용을 조금씩 나누어 읽으면서 데이터형이 다를 때 경고를 발생함
#df = pd.read_csv(output, encoding='utf-8', low_memory=False) #파일을 나누어 읽지 않고 한 번에 읽도록 함
df = pd.read_csv(output, encoding='utf-8', dtype={'ISBN': str, '부가기호': str, '주제분류번호': str}) #경고가 발생한 5,7,9열의 데이터 타입을 문자열(str)로 지정하여 읽음
df.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자,Unnamed: 13
0,1,플로우=Flow,긴츠 질발로디스 감독,노바미디어,2025,8809866320916,NaN,NaN,NaN,688.2,1,0,2026-06-30,NaN
1,2,투게더,마이클 생크스 감독,디온(The On),2026,8800279440390,NaN,NaN,NaN,688.2,1,0,2026-06-30,NaN
2,3,코트 스틸링,대런 아로노프스키 감독,소니픽쳐스,2026,8809763865411,NaN,NaN,NaN,688.2,1,0,2026-06-30,NaN
3,4,총알 탄 사나이,아키바 샤퍼 감독,파라마운트,2025,8809931179425,NaN,NaN,NaN,688.2,1,0,2026-06-30,NaN
4,5,인비저블 보이,가브리엘 살바토레스 감독,유케이미디어,2026,8800240308209,NaN,NaN,NaN,688.2,1,0,2026-06-30,NaN

In [6]:
import openpyxl
import xlsxwriter
df.to_excel('book2.xlsx', index=False, engine='xlsxwriter') #엑셀 파일로 저장, index=False: 인덱스 열을 저장하지 않음

# 2장 데이터 수집하기
##### (1) API 사용하기
##### (2) 웹 스크래핑 사용하기

In [7]:
# 파이썬 객체(딕셔너리, 딕셔너리 리스트)를 JSON 문자열로 변환하기
import json
d = {'name':'혼자 공부하는 데이터 분석'}
d_str = json.dumps(d, ensure_ascii=False)

print(type(d_str))

<class 'str'>

In [8]:
#JSON 문자열을 파이썬 객체로 변환하기
d2 = json.loads(d_str)
print(d2['name'])
print(type(d2))

d3 = json.loads('{"name": "혼자 공부하는 데이터 분석", "author": "박해선", "year": 2022}')
print(d3['name'])
print(d3['author'])
print(d3['year'])

혼자 공부하는 데이터 분석
<class 'dict'>
혼자 공부하는 데이터 분석
박해선
2022

In [9]:
#딕셔너리 내의 값이 리스트인 경우
d4_str = '{"name": "혼자 공부하는 데이터 분석", "author": ["박혜선", "홍길동"], "year": 2022}'
d4 = json.loads(d4_str)
print(d4["author"][0])
print(d4["author"][1])

#JSON 배열을 파이썬의 딕셔너리 리스트로 변환하는 경우
d5_str = """
[
    {"name": "혼자 공부하는 데이터 분석", "author": "박혜선", "year": 2022},
    {"name": "혼자 공부하는 머신러닝+딥러닝", "author": "박해선", "year": 2020}
]
"""
d5 = json.loads(d5_str)
print(d5[0]["name"])
print(d5[1]["name"])

박혜선
홍길동
혼자 공부하는 데이터 분석
혼자 공부하는 머신러닝+딥러닝

In [10]:
#XML문자열을 파이썬 객체로 변환하기
x_str = """
    <book> 
        <name>혼자 공부하는 데이터 분석</name>
        <author>박해선</author>
        <year>2022</year>
    </book>
"""
import xml.etree.ElementTree as et
book = et.fromstring(x_str) #book은 Element 객체로 부모 엘리먼트이고 name, author, year는 자식 엘리먼트임
name = book.find("name").text #name=book.findtext("name")과 동일
author = book.find("author").text
year = book.find("year").text
print(name, author, year)

#자식 엘리먼트가 여러 개 있는 경우
x_str2 = """
<books>
    <book> 
        <name>혼자 공부하는 데이터 분석</name>
        <author>박해선</author>
        <year>2022</year>
    </book>
    <book> 
        <name>혼자 공부하는 머신러닝+딥러닝</name>
        <author>박해선</author>
        <year>2020</year>
    </book>
</books>
"""
books = et.fromstring(x_str2) #books는 Element 객체로 부모 엘리먼트이고 book은 자식 엘리먼트임
for book in books.findall("book"):
    name = book.find("name").text
    author = book.find("author").text
    year = book.find("year").text
    print(name, author, year)

혼자 공부하는 데이터 분석 박해선 2022
혼자 공부하는 데이터 분석 박해선 2022
혼자 공부하는 머신러닝+딥러닝 박해선 2020

In [11]:
#JSON 문자열과 XML 문자열을 판다스 데이터프레임으로 변환하기
import io
import pandas as pd
d4_str = '{"name": "혼자 공부하는 데이터 분석", "author": ["박혜선", "홍길동"], "year": 2022}'
#pd.read_json(문자열): 문자열을 파일 경로로 인식함. StringIO()로 데이터 스트림임을 알려주어야 함
df4 = pd.read_json(io.StringIO(d4_str)) #StringIO는 문자열을 파일처럼 다룰 수 있도록 해주는 클래스임
print(df4)
df5 = pd.read_json(io.StringIO(d5_str))
print(df5)

print("XML 문자열을 판다스 데이터프레임으로 변환하기-1")
df6 = pd.read_xml(io.StringIO(x_str), xpath=".") #전체를 감싸는 태그가 없을 때는 xpath로 데이터의 시작점(현재 위치인 ., 이는 book임)을 지정해야 함
print(df6)
print("XML 문자열을 판다스 데이터프레임으로 변환하기-2")
df7 = pd.read_xml(io.StringIO(x_str2)) #book2 아래에 여러 개의 book이 있을 때는 xpath를 설정하지 않아도 됨
print(df7)

             name author  year
0  혼자 공부하는 데이터 분석    박혜선  2022
1  혼자 공부하는 데이터 분석    홍길동  2022
               name author  year
0    혼자 공부하는 데이터 분석    박혜선  2022
1  혼자 공부하는 머신러닝+딥러닝    박해선  2020
XML 문자열을 판다스 데이터프레임으로 변환하기-1
             name author  year
0  혼자 공부하는 데이터 분석    박해선  2022
XML 문자열을 판다스 데이터프레임으로 변환하기-2
               name author  year
0    혼자 공부하는 데이터 분석    박해선  2022
1  혼자 공부하는 머신러닝+딥러닝    박해선  2020

In [1]:
#Yes24 사이트에서 검색 결과 페이지 가져오기
import gdown
gdown.download("https://bit.ly/3q9SZix", '20s_best_book.json', quiet=False)

Downloading...
From: https://bit.ly/3q9SZix
To: e:\working\pythonBasic\HonGong-DataAnalysis_py\20s_best_book.json
100%|██████████| 92.9k/92.9k [00:00<00:00, 850kB/s]

'20s_best_book.json'

In [2]:
#JSON 파일을 읽어 판다스 데이터프레임으로 변환
import pandas as pd
books_df = pd.read_json('20s_best_book.json')
books_df.head(10)

,no,ranking,bookname,authors,publisher,publication_year,isbn13,addition_symbol,vol,class_no,class_nm,loan_count,bookImageURL
0,1,1,우리가 빛의 속도로 갈 수 없다면 :김초엽 소설,지은이: 김초엽,허블,2019,9791190090018,03810,,813.7,문학 > 한국문학 > 소설,461,https://image.aladin.co.kr/product/19359/16/co...
1,2,2,달러구트 꿈 백화점.이미예 장편소설,지은이: 이미예,팩토리나인,2020,9791165341909,03810,,813.7,문학 > 한국문학 > 소설,387,https://image.aladin.co.kr/product/24512/70/co...
2,3,3,지구에서 한아뿐 :정세랑 장편소설,지은이: 정세랑,난다,2019,9791188862290,03810,,813.7,문학 > 한국문학 > 소설,383,https://image.aladin.co.kr/product/19804/82/co...
3,4,4,"시선으로부터, :정세랑 장편소설",지은이: 정세랑,문학동네,2020,9788954672214,03810,,813.7,문학 > 한국문학 > 소설,370,https://image.aladin.co.kr/product/24131/37/co...
4,5,5,아몬드 :손원평 장편소설,지은이: 손원평,창비,2017,9788936434267,03810,,813.7,문학 > 한국문학 > 소설,365,http://image.aladin.co.kr/product/16839/4/cove...
5,6,6,피프티 피플 :정세랑 장편소설,지은이: 정세랑,창비,2016,9788936434243,03810,,813.7,문학 > 한국문학 > 소설,320,https://bookthumb-phinf.pstatic.net/cover/113/...
6,7,7,목소리를 드릴게요 :정세랑 소설집,지은이: 정세랑,아작,2020,9791165300005,03810,,813.7,문학 > 한국문학 > 소설,319,https://image.aladin.co.kr/product/22246/11/co...
7,8,8,나미야 잡화점의 기적 :히가시노 게이고 장편소설,지은이: 히가시노 게이고 ;옮긴이: 양윤옥,현대문학,2012,9788972756194,03830,,833.6,문학 > 일본문학 > 소설,312,http://image.aladin.co.kr/product/15848/6/cove...
8,9,9,선량한 차별주의자,김지혜 지음,창비,2019,9788936477196,03300,,334.0,"사회과학 > 사회학, 사회문제 > 사회문제",293,https://image.aladin.co.kr/product/19874/76/co...
9,10,9,쇼코의 미소 :최은영 소설,지은이: 최은영,문학동네,2016,9788954641630,03810,,813.7,문학 > 한국문학 > 소설,293,https://bookthumb-phinf.pstatic.net/cover/107/...

In [3]:
#원본 데이터프레임에서 no열에서 isbn13열까지 추출하여 새로운 데이터프레임 생성
books = books_df[['no', 'ranking', 'bookname', 'authors', 'publisher', 'publication_year', 'isbn13']]
books.head()

#loc 메소드로 행과 열을 선택함: loc[[],[]]에 첫 번째 []에는 행, 두 번째 []에는 열을 지정
books2 = books_df.loc[0:3, 'bookname':'authors'] 
books2.head()

                      bookname   authors
0  우리가 빛의 속도로 갈 수 없다면 :김초엽 소설   지은이: 김초엽
1         달러구트 꿈 백화점.이미예 장편소설   지은이: 이미예
2          지구에서 한아뿐 :정세랑 장편소설   지은이: 정세랑
3           시선으로부터, :정세랑 장편소설   지은이: 정세랑

In [4]:
#Beautiful Soup 임포트하기
from bs4 import BeautifulSoup
#객체 생성

#soup = BeautifulSoup(r.text, 'html.parser') #r은 requests.get(url)로 반환받은 Response 객체임

# 3장 데이터 정제하기
##### (1) 불필요한 데이터 삭제하기
##### (2) 잘못된 데이터 수정하기

In [ ]:
#gdown 패키지로 데이터 (남산도서관)다운로드
#import gdown
#gdown.download('https://bit.ly/3RhoNho', 'ns_202104.csv', quiet=False)

In [1]:
#판다스 데이터프레임으로 읽고 확인을 위해 앞의 몇 줄 출력
import pandas as pd
ns_df = pd.read_csv('ns_202104.csv', low_memory=False)
#ns_df.head() #기본값으로 5줄 출력, CSV 파일의 각 행의 끝에 있는 콤마로 인해 Unnamed: 13열이 생성된 것임

In [2]:
#loc 메소드로 열을 선택하여 새로운 데이터프레임을 만듦
ns_book = ns_df.loc[:, '번호':'등록일자']
#ns_book.head()

In [3]:
#위에서 '번호'에서 '등록일자' 사이의 열을 제외하려면 불리언 배열을 사용해야 함
print(ns_book.columns)
selected_columns = ns_df.columns != 'Unnamed: 13'
ns_book = ns_df.loc[:, selected_columns]
#ns_book.head()

Index(['번호', '도서명', '저자', '출판사', '발행년도', 'ISBN', '세트 ISBN', '부가기호', '권',
       '주제분류번호', '도서권수', '대출건수', '등록일자'],
      dtype='str')

In [4]:
#데이터프레임의 drop()메소드를 사용한 열 삭제
ns_book = ns_df.drop('Unnamed: 13', axis=1) #axis=1은 열을 지정한 것임
ns_book.head()
ns_book = ns_df.drop('부가기호', axis=1) 
#ns_book.head()
ns_book = ns_df.drop(['Unnamed: 13', '부가기호'], axis=1) #여러 열을 제외
#ns_book.head()

In [5]:
#데이터프레임 자체에서 열을 제외시킴->새로운 데이터프레임을 생성하지 않음
ns_book.drop('주제분류번호', axis=1, inplace=True) #inplace=True이면 자체 업데이트함
ns_book.head()
print(ns_book.columns)

Index(['번호', '도서명', '저자', '출판사', '발행년도', 'ISBN', '세트 ISBN', '권', '도서권수',
       '대출건수', '등록일자'],
      dtype='str')

In [6]:
#데이터프레임에서 하나이상의 NaN이 포함된 행이나 열을 삭제함
ns_book2 = ns_df.dropna(axis=1) #열을 삭제함
ns_book2.head()

   번호           ISBN  도서권수  대출건수        등록일자
0   1  9788937444319     1     0  2021-03-19
1   2  9791190123969     1     0  2021-03-19
2   3  9788968332982     1     0  2021-03-19
3   4  9788970759906     1     0  2021-03-19
4   5  9788934990833     1     0  2021-03-19

In [7]:
#행 삭제하기: drop() 메소드 사용
print(ns_book2.columns)
ns_book3 = ns_book2.drop([0,1,3], axis=0)
ns_book3.head()

Index(['번호', 'ISBN', '도서권수', '대출건수', '등록일자'], dtype='str')

   번호           ISBN  도서권수  대출건수        등록일자
2   3  9788968332982     1     0  2021-03-19
4   5  9788934990833     1     0  2021-03-19
5   6  9791189550370     1     0  2021-03-19
6   7  9791160075793     1     0  2021-03-19
7   8  9788960906679     1     0  2021-03-19

In [8]:
#행 삭제하기: []와 슬라이싱 사용
ns_book4 = ns_book2[2:5]
ns_book4.head()

   번호           ISBN  도서권수  대출건수        등록일자
2   3  9788968332982     1     0  2021-03-19
3   4  9788970759906     1     0  2021-03-19
4   5  9788934990833     1     0  2021-03-19

In [9]:
#행 삭제하기: []와 불리언 배열 사용
selected_rows = ns_df['출판사']=='한빛미디어'
ns_book6 = ns_book[selected_rows]
#ns_book6.head()

In [10]:
#중복된 행 찾기: duplicated() 메소드 사용->중복된 행은 True, 아닌 행은 False로 불리언 배열 반환
sum(ns_book.duplicated()) #sum() 계산에서 True은 1로 계산함
#중복을 판단할 열을 지정할 수 있음
print(ns_book.columns)
sum(ns_book.duplicated(subset=['도서명', '저자', 'ISBN']))
#중복된 모든 행을 True로 표시한 불리언 배열을 반환하여 모든 중복된 행을 출력함: keep=False로 지정
dup_rows = ns_book.duplicated(subset=['도서명', '저자', 'ISBN'], keep=False)
ns_book3 = ns_book[dup_rows]
#ns_book3.head()

Index(['번호', '도서명', '저자', '출판사', '발행년도', 'ISBN', '세트 ISBN', '권', '도서권수',
       '대출건수', '등록일자'],
      dtype='str')

In [11]:
#그룹별로 모으기: 같은 도서의 대출건수를 하나로 합침, groupby() 메소드 사용
count_df = ns_book[['도서명', '저자', 'ISBN', '권', '대출건수']]
count_df.head()
group_df = count_df.groupby(by=['도서명', '저자', 'ISBN', '권'], dropna=False) #NaN 행을 삭제하지 않음
#group_df.head()
loan_count = group_df.sum()
#loan_count.head()

In [16]:
#대출건수를 원본 데이터에 업데이트하기
dup_rows = ns_book.duplicated(subset=['도서명','저자','ISBN','권']) #중복된 행은 True로 표시
unique_rows = ~dup_rows #중복되지 않을 행을 True로 표시
ns_book7 = ns_book[unique_rows].copy() #고유한 행만 선택하여 새로 저장함
ns_book7.set_index(['도서명','저자','ISBN','권'], inplace=True) #새로운 데이터프레임을 만들지 않고 자체 데이터프레임 내에 수정
#loan_count 배열로 대출건수 데이터를 업데이트함
#print(ns_book7.index)
#print(loan_count.index)
loan_count_clean = loan_count.reset_index().dropna(subset=['도서명','저자','ISBN','권'])
loan_count_clean.set_index(['도서명','저자','ISBN','권'], inplace=True)
ns_book7.update(loan_count_clean) #인덱스에 결측치(NaN)이 있으면 오류가 발생함
ns_book7.head()
ns_book7 = ns_book7.reset_index()
print(sum(ns_book['대출건수']>100))
print(sum(ns_book7['대출건수']>100))

2311
2223

In [13]:
#쉬어가기: 수동으로 데이터프레임 만들기, 행 인덱스, 열 이름
import pandas as pd
import numpy as np
df1 = pd.DataFrame({
    'A': [1, 2, np.nan, 4], #A열의 데이터
    'B': [10, np.nan, 30, 40] #B열의 데이터
}, index=['a', 'b', 'c', 'd']) #행 인덱스(4개의 행)
df1.head()

     A     B
a  1.0  10.0
b  2.0   NaN
c  NaN  30.0
d  4.0  40.0

In [21]:
#불필요한 행과 열을 제거하는 일괄처리 함수 만들기
def data_cleaning(filename):
    ns_df = pd.read_csv(filename, low_memory=False)
    ns_book = ns_df.dropna(axis=1, how='all') #열이 모두 NaN인 열을 삭제함
    count_df = ns_book[['도서명', '저자', 'ISBN', '권', '대출건수']]
    loan_count = count_df.groupby(by=['도서명', '저자', 'ISBN', '권'], dropna=False).sum()
    dup_rows = ns_book.duplicated(subset=['도서명', '저자', 'ISBN', '권'])
    ns_book3 = ns_book[~dup_rows].copy()
    loan_count_clean = loan_count.reset_index().dropna(subset=['도서명','저자','ISBN','권'])
    loan_count_clean.set_index(['도서명','저자','ISBN','권'], inplace=True)
    ns_book3.update(loan_count_clean)
    ns_book4 = ns_book3.reset_index()
    ns_book4 = ns_book4[ns_book.columns]
    return ns_book4

In [22]:
new_ns_book4 = data_cleaning('ns_202104.csv')
ns_book4.equals(new_ns_book4) #데이터프레임끼리 비교할 때 equals() 사용

False

# 4장 데이터 요약하기
##### (1) 통계로 요약하기
##### (2) 분포 요약하기

# 5장 데이터 시각화하기
##### (1) 맷플롭립 기본 요소 알아보기
##### (2) 선 그래프와 막대 그래프 그리기

# 6장 복잡한 데이터 표현하기
##### (1) 객체지향 API로 그래프 꾸미기
##### (2) 맷플롭립의 고급 기능 배우기

# 7장 검증하고 예측하기
##### (1) 통계적으로 추론하기
##### (2) 머신러닝으로 예측하기