# 1장 데이터 분석을 시작하며
##### (1) 데이터 분석이란
##### (2) 구글 코랩과 주피터 노트북
##### (3) 이 도서가 얼마나 인기가 좋을까요?

In [27]:
output ="서울특별시교육청남산도서관 장서 대출목록 (2026년 06월).csv"
import pandas as pd
df = pd.read_csv(output, encoding='utf-8')
print(df.head())

   번호        도서명             저자         출판사  발행년도           ISBN  세트 ISBN  \
0   1  플로우=Flow     긴츠 질발로디스 감독       노바미디어  2025  8809866320916      NaN
1   2        투게더     마이클 생크스 감독  디온(The On)  2026  8800279440390      NaN
2   3     코트 스틸링   대런 아로노프스키 감독       소니픽쳐스  2026  8809763865411      NaN
3   4   총알 탄 사나이      아키바 샤퍼 감독       파라마운트  2025  8809931179425      NaN
4   5    인비저블 보이  가브리엘 살바토레스 감독      유케이미디어  2026  8800240308209      NaN

  부가기호    권 주제분류번호  도서권수  대출건수        등록일자  Unnamed: 13
0  NaN  NaN  688.2     1     0  2026-06-30          NaN
1  NaN  NaN  688.2     1     0  2026-06-30          NaN
2  NaN  NaN  688.2     1     0  2026-06-30          NaN
3  NaN  NaN  688.2     1     0  2026-06-30          NaN
4  NaN  NaN  688.2     1     0  2026-06-30          NaN

C:\Users\yccho\AppData\Local\Temp\ipykernel_25584\4197475141.py:3: DtypeWarning: Columns (0: ISBN, 1: 부가기호, 2: 주제분류번호) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(output, encoding='utf-8')

In [28]:
with open(output, encoding="utf-8") as f:
    print(f.readline()) #한 줄만 읽어옴
    print(f.readline())

번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자,

"1","플로우=Flow ","긴츠 질발로디스 감독","노바미디어","2025","8809866320916","","","","688.2","1","0","2026-06-30",

In [29]:
#파일 인코딩 형식 확인하기
import chardet
with open(output, 'rb') as f:
    d=f.readline()
    print(chardet.detect(d))

{'encoding': 'UTF-8-SIG', 'confidence': 1.0, 'language': 'ko', 'mime_type': 'text/plain'}

* CSV 파일을 데이터프레임으로 읽기: read_csv()

In [30]:
import pandas as pd
#df = pd.read_csv(output, encoding='utf-8') #5,7,9열은 혼합된 데이터가 저장되어 있음을 경고함->파일 내용을 조금씩 나누어 읽으면서 데이터형이 다를 때 경고를 발생함
#df = pd.read_csv(output, encoding='utf-8', low_memory=False) #파일을 나누어 읽지 않고 한 번에 읽도록 함
df = pd.read_csv(output, encoding='utf-8', dtype={'ISBN': str, '부가기호': str, '주제분류번호': str}) #경고가 발생한 5,7,9열의 데이터 타입을 문자열(str)로 지정하여 읽음
df.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자,Unnamed: 13
0,1,플로우=Flow,긴츠 질발로디스 감독,노바미디어,2025,8809866320916,NaN,NaN,NaN,688.2,1,0,2026-06-30,NaN
1,2,투게더,마이클 생크스 감독,디온(The On),2026,8800279440390,NaN,NaN,NaN,688.2,1,0,2026-06-30,NaN
2,3,코트 스틸링,대런 아로노프스키 감독,소니픽쳐스,2026,8809763865411,NaN,NaN,NaN,688.2,1,0,2026-06-30,NaN
3,4,총알 탄 사나이,아키바 샤퍼 감독,파라마운트,2025,8809931179425,NaN,NaN,NaN,688.2,1,0,2026-06-30,NaN
4,5,인비저블 보이,가브리엘 살바토레스 감독,유케이미디어,2026,8800240308209,NaN,NaN,NaN,688.2,1,0,2026-06-30,NaN

In [31]:
import openpyxl
import xlsxwriter
df.to_excel('book2.xlsx', index=False, engine='xlsxwriter') #엑셀 파일로 저장, index=False: 인덱스 열을 저장하지 않음

# 2장 데이터 수집하기
##### (1) API 사용하기
##### (2) 웹 스크래핑 사용하기

In [32]:
# 파이썬 객체(딕셔너리, 딕셔너리 리스트)를 JSON 문자열로 변환하기
import json
d = {'name':'혼자 공부하는 데이터 분석'}
d_str = json.dumps(d, ensure_ascii=False)

print(type(d_str))

<class 'str'>

In [33]:
#JSON 문자열을 파이썬 객체로 변환하기
d2 = json.loads(d_str)
print(d2['name'])
print(type(d2))

d3 = json.loads('{"name": "혼자 공부하는 데이터 분석", "author": "박해선", "year": 2022}')
print(d3['name'])
print(d3['author'])
print(d3['year'])

혼자 공부하는 데이터 분석
<class 'dict'>
혼자 공부하는 데이터 분석
박해선
2022

In [ ]:
#딕셔너리 내의 값이 리스트인 경우
d4_str = '{"name": "혼자 공부하는 데이터 분석", "author": ["박혜선", "홍길동"], "year": 2022}'
d4 = json.loads(d4_str)
print(d4["author"][0])
print(d4["author"][1])

#JSON 배열을 파이썬의 딕셔너리 리스트로 변환하는 경우
d5_str = """
[
    {"name": "혼자 공부하는 데이터 분석", "author": "박혜선", "year": 2022},
    {"name": "혼자 공부하는 머신러닝+딥러닝", "author": "박해선", "year": 2020}
]
"""
d5 = json.loads(d5_str)
print(d5[0]["name"])
print(d5[1]["name"])

박혜선
홍길동
혼자 공부하는 데이터 분석
혼자 공부하는 머신러닝+딥러닝

In [57]:
#XML문자열을 파이썬 객체로 변환하기
x_str = """
    <book> 
        <name>혼자 공부하는 데이터 분석</name>
        <author>박해선</author>
        <year>2022</year>
    </book>
"""
import xml.etree.ElementTree as et
book = et.fromstring(x_str) #book은 Element 객체로 부모 엘리먼트이고 name, author, year는 자식 엘리먼트임
name = book.find("name").text #name=book.findtext("name")과 동일
author = book.find("author").text
year = book.find("year").text
print(name, author, year)

#자식 엘리먼트가 여러 개 있는 경우
x_str2 = """
<books>
    <book> 
        <name>혼자 공부하는 데이터 분석</name>
        <author>박해선</author>
        <year>2022</year>
    </book>
    <book> 
        <name>혼자 공부하는 머신러닝+딥러닝</name>
        <author>박해선</author>
        <year>2020</year>
    </book>
</books>
"""
books = et.fromstring(x_str2) #books는 Element 객체로 부모 엘리먼트이고 book은 자식 엘리먼트임
for book in books.findall("book"):
    name = book.find("name").text
    author = book.find("author").text
    year = book.find("year").text
    print(name, author, year)

혼자 공부하는 데이터 분석 박해선 2022
혼자 공부하는 데이터 분석 박해선 2022
혼자 공부하는 머신러닝+딥러닝 박해선 2020

In [72]:
#JSON 문자열과 XML 문자열을 판다스 데이터프레임으로 변환하기
import io
import pandas as pd
d4_str = '{"name": "혼자 공부하는 데이터 분석", "author": ["박혜선", "홍길동"], "year": 2022}'
#pd.read_json(문자열): 문자열을 파일 경로로 인식함. StringIO()로 데이터 스트림임을 알려주어야 함
df4 = pd.read_json(io.StringIO(d4_str)) #StringIO는 문자열을 파일처럼 다룰 수 있도록 해주는 클래스임
print(df4)
df5 = pd.read_json(io.StringIO(d5_str))
print(df5)

print("XML 문자열을 판다스 데이터프레임으로 변환하기-1")
df6 = pd.read_xml(io.StringIO(x_str), xpath=".") #전체를 감싸는 태그가 없을 때는 xpath로 데이터의 시작점(현재 위치인 ., 이는 book임)을 지정해야 함
print(df6)
print("XML 문자열을 판다스 데이터프레임으로 변환하기-2")
df7 = pd.read_xml(io.StringIO(x_str2)) #book2 아래에 여러 개의 book이 있을 때는 xpath를 설정하지 않아도 됨
print(df7)

             name author  year
0  혼자 공부하는 데이터 분석    박혜선  2022
1  혼자 공부하는 데이터 분석    홍길동  2022
               name author  year
0    혼자 공부하는 데이터 분석    박혜선  2022
1  혼자 공부하는 머신러닝+딥러닝    박해선  2020
XML 문자열을 판다스 데이터프레임으로 변환하기-1
             name author  year
0  혼자 공부하는 데이터 분석    박해선  2022
XML 문자열을 판다스 데이터프레임으로 변환하기-2
               name author  year
0    혼자 공부하는 데이터 분석    박해선  2022
1  혼자 공부하는 머신러닝+딥러닝    박해선  2020

In [74]:
#Yes24 사이트에서 검색 결과 페이지 가져오기
import gdown
gdown.download("https://bit.ly/3q9SZix", '20s_best_book.json', quiet=False)

Downloading...
From: https://bit.ly/3q9SZix
To: e:\working\pythonBasic\HonGong-DataAnalysis_py\20s_best_book.json
100%|██████████| 92.9k/92.9k [00:00<00:00, 1.79MB/s]

'20s_best_book.json'

In [75]:
#JSON 파일을 읽어 판다스 데이터프레임으로 변환
import pandas as pd
books_df = pd.read_json('20s_best_book.json')
books_df.head()

,no,ranking,bookname,authors,publisher,publication_year,isbn13,addition_symbol,vol,class_no,class_nm,loan_count,bookImageURL
0,1,1,우리가 빛의 속도로 갈 수 없다면 :김초엽 소설,지은이: 김초엽,허블,2019,9791190090018,03810,,813.7,문학 > 한국문학 > 소설,461,https://image.aladin.co.kr/product/19359/16/co...
1,2,2,달러구트 꿈 백화점.이미예 장편소설,지은이: 이미예,팩토리나인,2020,9791165341909,03810,,813.7,문학 > 한국문학 > 소설,387,https://image.aladin.co.kr/product/24512/70/co...
2,3,3,지구에서 한아뿐 :정세랑 장편소설,지은이: 정세랑,난다,2019,9791188862290,03810,,813.7,문학 > 한국문학 > 소설,383,https://image.aladin.co.kr/product/19804/82/co...
3,4,4,"시선으로부터, :정세랑 장편소설",지은이: 정세랑,문학동네,2020,9788954672214,03810,,813.7,문학 > 한국문학 > 소설,370,https://image.aladin.co.kr/product/24131/37/co...
4,5,5,아몬드 :손원평 장편소설,지은이: 손원평,창비,2017,9788936434267,03810,,813.7,문학 > 한국문학 > 소설,365,http://image.aladin.co.kr/product/16839/4/cove...

In [90]:
#원본 데이터프레임에서 no열에서 isbn13열까지 추출하여 새로운 데이터프레임 생성
books = books_df[['no', 'ranking', 'bookname', 'authors', 'publisher', 'publication_year', 'isbn13']]
books.head()

#loc 메소드로 행과 열을 선택함: loc[[],[]]에 첫 번째 []에는 행, 두 번째 []에는 열을 지정
books2 = books_df.loc[0:3, 'bookname':'authors'] 
books2.head()

                      bookname   authors
0  우리가 빛의 속도로 갈 수 없다면 :김초엽 소설   지은이: 김초엽
1         달러구트 꿈 백화점.이미예 장편소설   지은이: 이미예
2          지구에서 한아뿐 :정세랑 장편소설   지은이: 정세랑
3           시선으로부터, :정세랑 장편소설   지은이: 정세랑

In [ ]:
#Beautiful Soup 임포트하기
from bs4 import BeautifulSoup
#객체 생성

#soup = BeautifulSoup(r.text, 'html.parser') #r은 requests.get(url)로 반환받은 Response 객체임

# 3장 데이터 정제하기
##### (1) 불필요한 데이터 삭제하기
##### (2) 잘못된 데이터 수정하기

# 4장 데이터 요약하기
##### (1) 통계로 요약하기
##### (2) 분포 요약하기

# 5장 데이터 시각화하기
##### (1) 맷플롭립 기본 요소 알아보기
##### (2) 선 그래프와 막대 그래프 그리기

# 6장 복잡한 데이터 표현하기
##### (1) 객체지향 API로 그래프 꾸미기
##### (2) 맷플롭립의 고급 기능 배우기

# 7장 검증하고 예측하기
##### (1) 통계적으로 추론하기
##### (2) 머신러닝으로 예측하기